[package]
name = "graphql-example"
version = "0.1.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.6.2"
tokio = { version = "1.4.0", features = ["rt", "macros"] }
serde_json = "1.0.64"
lamedh_runtime = "0.3.0"
lamedh_http = "0.3.0"
thiserror = "1.0.38"
aws_lambda_events = "0.4.0"
http = "0.2.8"
sqlx = { version = "0.5.1", features = [ "runtime-tokio-rustls", "postgres", "macros" ] }
tracing = "0.1.25"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.2.17", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = { version = "0.2.0", default-features = false }
tracing-log = "0.1.3"

